version: '3'

services:

  app:
    image: asuvorina/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    command: bash -c "npm test"
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  pgdata:
