name: ci

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2      
      - run: make ci
  build:
    needs: ci
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: asuvorina/devops-for-programmers-project-lvl1:latest
